//! Represents the top-level structure of a successful response from the Gemini API.
//!
//! Contains a list of candidate responses generated by the model.
//! This is the primary structure for deserializing the API JSON response.
//! Uses fully qualified paths for dependencies.
//! Contains `Candidate` items.

#[derive(Debug, serde::Deserialize)]
pub struct ApiResponse {
    pub candidates: std::vec::Vec<crate::vendors::gemini::candidate::Candidate>,
}
