//! Represents the content part of a candidate response in the Gemini API.
//!
//! Holds the list of response parts (usually text) generated by the model.
//! This structure mirrors the input `Content` structure but for the response.
//! Uses fully qualified paths for dependencies.
//! Part of the `Candidate` structure.

#[derive(Debug, serde::Deserialize)]
pub struct ContentResponse {
    /// Output only. The producer of the content. Must be either 'user' or 'model'.
    // This field is part of the Gemini API's GenerateContentResponse.Candidate.Content structure.
    pub role: Option<crate::vendors::gemini::role::Role>,
    pub parts: std::vec::Vec<crate::vendors::gemini::part_response::PartResponse>,
}
