//! Defines the OpenAPI v3 specification for the AgentLoop API.
//!
//! This module uses `utoipa` to generate the OpenAPI specification by manually
//! defining paths and components, adhering to the strict project guidelines
//! that prevent direct annotation of handler functions.
//! It aggregates information about API routes, request/response types, and security.

//! Revision History
//! - 2025-04-25T13:50:59Z @AI: Initial implementation based on task instruction.

// Note: Fully qualified paths are used throughout as per guidelines.

use utoipa::OpenApi;

/// Represents the OpenAPI documentation structure for the AgentLoop API.
///
/// The `#[openapi]` macro configures the entire specification, including paths,
/// components (schemas, security schemes), and tags.
#[derive(utoipa::OpenApi)]
#[openapi(
    // Define API paths manually, linking them to conceptual operations.
    paths(
        // Research endpoint
        crate::handlers::start_research::start_research, // Utoipa path macro is on the function
        // Session status endpoint
        crate::handlers::get_status::get_status, // Utoipa path macro is on the function
        // Post message to session endpoint
        crate::handlers::post_message::post_message, // Utoipa path macro is on the function
        // Terminate session endpoint
        crate::handlers::terminate_session::terminate_session, // Utoipa path macro is on the function
        // WebSocket conversation stream endpoint
        crate::handlers::conversation_stream::conversation_stream // Utoipa path macro is on the function
    ),
    // Define reusable components like data schemas and security schemes.
    components(
        // Schemas used in request/response bodies or path parameters.
        schemas(
            crate::types::research_request::ResearchRequest,
            crate::types::status_response::StatusResponse,
            crate::types::message::Message,
            crate::types::ws_request::WebsocketRequest, // Added schema
            crate::types::ws_event::WebsocketEvent, // Added schema for potential documentation
            crate::types::session_status::SessionStatus, // Added enum schema
            crate::types::sender::Sender, // Added enum schema
            crate::types::context_evaluator_feedback::ContextEvaluatorFeedback, // Added struct schema
            // Define inline schema for start_research response if needed, or create a dedicated type
            // Example inline: utoipa::schema!(#[aliases(SessionStartResponse = inline {"session_id": String})])
            // For simplicity, we assume the handler's utoipa::path provides this info.
            // If not, a dedicated response type would be cleaner.
            // Example dedicated type (would need its own file per guidelines):
            // crate::types::session_start_response::SessionStartResponse
            // For now, rely on handler annotation if possible, otherwise add inline/dedicated type later.
        ),
    ),
    // Define tags for grouping related API endpoints.
    tags(
        (name = "Loupe", description = "AgentLoop Session Management API"), // Use tag from handlers
        (name = "Research", description = "Endpoints for initiating research tasks"),
        (name = "Session", description = "Endpoints for managing session lifecycle and interaction")
    ),
    // Define global security requirements (optional).
    // Example: Apply bearer_auth globally: #[openapi(security(("bearer_auth" = [])))]
    // Apply security based on middleware in main.rs/app_setup.rs
    security(
        ("bearer_auth" = []) // Apply Bearer Authentication globally
    ),
    // Optional: Define external documentation.
    // external_docs(url = "...", description = "...")
)]
pub struct ApiDoc;

/// Generates the OpenAPI specification document.
///
/// This function leverages the `ApiDoc::openapi()` method generated by the
/// `utoipa::OpenApi` derive macro to produce the final OpenAPI object.
///
/// # Returns
///
/// An `utoipa::openapi::OpenApi` object representing the API specification.
pub fn api_doc() -> utoipa::openapi::OpenApi {
    ApiDoc::openapi()
}

// No tests included in this file as it primarily defines the OpenAPI structure.
// Testing would involve generating the spec and validating its content/format,
// potentially in integration tests or using external validation tools.
#[cfg(test)]
mod tests {
    #[test]
    fn test_generate_openapi_spec() {
        // Generate the spec
        let spec = super::api_doc();
        // Basic assertion: Check if generation succeeded and produced a non-empty spec
        assert!(!spec.paths.paths.is_empty(), "OpenAPI spec should have paths defined.");
        assert!(!spec.components.as_ref().unwrap().schemas.is_empty(), "OpenAPI spec should have schemas defined.");
        // Optional: Serialize to JSON and print/validate
        // let spec_json = serde_json::to_string_pretty(&spec).expect("Failed to serialize spec to JSON");
        // println!("{}", spec_json); // Print for manual inspection during test run
        // Add more specific assertions here if needed, e.g., checking for specific paths or schemas.
        assert!(spec.tags.iter().any(|tag| tag.name == "Loupe"));
        assert!(spec.components.as_ref().unwrap().security_schemes.contains_key("bearer_auth"));
    }
}

