//! Defines the structure for receiving a summary response from the LLM.
//!
//! This structure is used as the target type for the `llm_typed` function
//! when requesting conversation summarization. It ensures the LLM response
//! adheres to a predictable format containing the summary text.
//! Follows project guidelines.

// Note: Using FQNs as per guidelines.
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// Represents the expected structure of a summary generated by the LLM.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct LlmSummaryResponse {
    /// The generated summary text.
    pub summary: std::string::String,
}

impl llm::few_shots_traits::FewShotsOutput<LlmSummaryResponse> for LlmSummaryResponse {
    fn few_shots() -> std::vec::Vec<LlmSummaryResponse> {
        std::vec![
            LlmSummaryResponse {
                summary: std::string::String::from("The user asked for help and the agent responded."),
            },
            LlmSummaryResponse {
                summary: std::string::String::from("A discussion about Rust programming language features, focusing on borrowing and lifetimes. The user expressed confusion, and the agent provided examples."),
            },
        ]
    }
}

// No tests needed for a simple data structure with trait derives/impls.
