//! Defines the `LlmTypedLog` struct for structured logging of LLM interactions.
//!
//! This file contains a single primary Rust item, the `LlmTypedLog` struct,
//! adhering to the "one item per file" principle from the coding standards.
//! The struct is designed to capture detailed information about typed requests
//! to and responses from Large Language Models (LLMs), including metadata,
//! token counts, and payloads. It is intended for internal use within the
//! `llm_typed_unified` module.

// Allowed for derive macros as per rust_guidelines.
use serde::Serialize;

/// Represents a structured log entry for a typed LLM interaction.
///
/// Instances of this struct are typically serialized to record the specifics of
/// an LLM call, such as the model used, prompt and completion token counts,
/// the actual request and response payloads (as JSON values for flexibility),
/// and any errors encountered.
///
/// Visibility: `pub(super)` makes this struct visible to the parent module (`llm_typed_unified`),
/// suiting its role as an internal data structure for that module.
/// Fields are public for direct access, common for data-centric structs.
#[derive(Serialize)]
pub(super) struct LlmTypedLog {
    /// Optional unique identifier for the specific LLM request.
    pub request_id: std::option::Option<std::string::String>,

    /// Timestamp indicating when the log entry was generated (e.g., ISO 8601 format).
    pub timestamp: std::string::String,

    /// Identifier for the LLM model invoked (e.g., "gpt-4-turbo").
    pub model_name: std::string::String,

    /// Number of tokens in the input prompt provided to the LLM.
    pub prompt_tokens: std::option::Option<u32>,

    /// Number of tokens in the completion generated by the LLM.
    pub completion_tokens: std::option::Option<u32>,

    /// Total tokens processed (sum of prompt and completion tokens).
    pub total_tokens: std::option::Option<u32>,

    /// The serialized request payload sent to the LLM.
    /// Stored as `serde_json::Value` for flexibility across different request types.
    pub request_payload: serde_json::Value,

    /// The serialized response payload received from the LLM.
    /// Stored as `serde_json::Value` for flexibility across different response types.
    pub response_payload: serde_json::Value,

    /// Optional message detailing any error that occurred during the LLM interaction.
    pub error_message: std::option::Option<std::string::String>,

    /// Duration of the LLM call in milliseconds.
    pub duration_ms: std::option::Option<u64>,
}

// Note: As per rust_guidelines, if this struct had an `impl` block, it would also reside here.
// Tests for functions are in the same file; structs generally don't have standalone tests
// in the same way unless they have methods with complex logic.